### ISSUE TITLE
is it working?

### ISSUE THREAD

**Issue by popthink** [crawlkit/crawlkit#111]
only scripts for extracting title are working for me..

I copied 'usage script' and modified 'some URL'.

But it doesn't work.

Just hanging without any output.

**Comment by joscha** [comment]
can you paste the code you are using?

**Comment by popthink** [comment]
`
'use strict'; // eslint-disable-line
const CrawlKit = require('crawlkit');
const genericAnchors = require('crawlkit/finders/genericAnchors');
const urijs = require('urijs');

class DomainLinkFinder {
  getRunnable() {
    // the function returned here runs within the webpage. No closures, etc.
    return genericAnchors;
  }
 urlFilter(url) {
    console.log(url);
    return url;
  }
}

var crawler = new CrawlKit('http://www.daum.net');
crawler.setFinder(new DomainLinkFinder());

crawler.concurrency = 15;
crawler.followRedirects = true;

crawler.crawl()
  .then((results) => {
    console.log(JSON.stringify(results, true, 2));
  }, (err) => console.error(err));
`
Here it is.

Thank you.

URLs are printed by log function. But... After that nothing happens.

**Comment by joscha** [comment]
I think you might want to restrict the search to the same domain - see `SameDomainLinkFinder` in `examples/advanced.js`. Also, I noticed when running it with debug mode (`DEBUG=* node examples/daum.js`) there are quite a few search links like `http://search.daum.net/search?w=cafe&DA=CCB&q=%EB%82%A8%EC%A4%91%EA%B5%AD%ED%95%B4%20%ED%8C%90%EA%B2%B0&m=boa`, etc. You might want to exclude those URLs as they are potentially endless.
