### ISSUE TITLE
Add prepublish step

### ISSUE THREAD

**Issue by tolmasky** [crawlkit/crawlkit#18]
Hi, we almost have this working in tonic now, its just that this uses full es6 which requires the user to have set up a require-hook. If you add a prepublish step that converts it, it will work out of the box with tonic (and any vanilla install of node as well).

It would be as easy as adding the following to your package.son:

```
  "scripts": {
    "compile": "babel -d lib/ src/",
    "prepublish": "npm run compile"
  }
```

and putting your current code in src. This is detailed further here: http://mammal.io/articles/using-es6-today/ and is used by many popular libraries like react grid: https://github.com/STRML/react-grid-layout .

**Comment by joscha** [comment]
Hi @tolmasky it doesn't use full es6, only the subset that Node supports currently - it will work with a vanilla install of any node above 4.2 - Babel is not needed.

**Comment by tolmasky** [comment]
I see, this should start working for us next week when we ship node 4 then. I suppose in none-node-4 we can just catch the syntax error, check the package json for the node 4 requirement, and let users know thats why its not working.

**Comment by joscha** [comment]
Or you could just read the `engine` section of the package? Like here: https://github.com/crawlkit/crawlkit/blob/master/package.json#L57

**Comment by tolmasky** [comment]
Right, thats what I meant by "check the package json for the node 4 requirement". What i was saying was, if it is required in non-node-4, try to use it unconditionally (without paying the cost of doing a package.json read/check), then only on error check if the reason for the error is a node-mismatch. If not, we need to start pre-checking every required module for node compatibility (which is also unfortunate because a lot of old modules haven't updated it despite working fine in older versions)

**Comment by joscha** [comment]
Right, that makes total sense :+1: - so shall I close this issue and just check back with tonic next week or is there anything else I should do now?

**Comment by joscha** [comment]
closing this for now as not a shortcoming of crawlkit itself.
