### ISSUE TITLE
Timeout not respected?

### ISSUE THREAD

**Issue by badtant** [crawlkit/crawlkit#235]
According to the docs, the default timeout is 30000.
I'm getting this error:
TimeoutError: Runner timed out after 10000ms.

Even if I set the timeout crawler.timeout = 40000 it will break after 10000.

**Comment by joscha** [comment]
Each runner has its own timeout (default is 10s), which is smaller than the one from the crawler - you can increase it via this API: https://doclets.io/crawlkit/crawlkit/master#dl-Runnable-timeout

**Comment by badtant** [comment]
Ah, ok. So if I run aXe runner. How do I specify the timeout for that?

Thanks

**Comment by joscha** [comment]
You can either subclass the runner:

```js
import AxeRunner from 'runner-axe';

class MyBigTimeoutAxeRunner extends AxeRunner {
 get timeout() {
   return 60 * 1000; // 60s
 }
}

crawler.addRunner('axe', new MyBigTimeoutAxeRunner());
````

or I suspect that you can also just set it on the object at runtime and it should work (untested and technically not clean):

```js
import AxeRunner from 'runner-axe';

const axeRunner = new AxeRunner();
axeRunner.timeout = 60 * 1000; // 60s
crawler.addRunner('axe', axeRunner);
```

**Comment by badtant** [comment]
Thanks!
