### ISSUE TITLE
Setting viewportSize?

### ISSUE THREAD

**Issue by badtant** [crawlkit/crawlkit#236]
Hi,

Is there a way to specify the viewportSize for phantom to use?
Didn't seem to be part of the settings obj.

Niklas

**Comment by joscha** [comment]
Seems to be a page-level property (
http://phantomjs.org/api/webpage/property/viewport-size.html) - you should
be able to pass them through via `phantomPageSettings`.

**Comment by badtant** [comment]
yeah, this seem to do the trick

```
crawler.phantomPageSettings = {
      'viewportSize': { width: 1440, height: 900 }
};
```
