### ISSUE TITLE
access to phantom object

### ISSUE THREAD

**Issue by bazjapan** [crawlkit/crawlkit#34]
Hi,
Does crawllkit allow access the phantom object or the page object?
 I'd like to for example use
phantom.addCookie

**Comment by joscha** [comment]
currently, that is abstracted away, however you can add cookies via the [`CrawlKit.browserCookies`](http://crawlkit.github.io/crawlkit/docs/CrawlKit.html#browserCookies) API, like:

``` javascript
const crawler = new CrawlKit();
crawler.browserCookies = [
    {
        'name'     : 'Valid-Cookie-Name',   /* required property */
        'value'    : 'Valid-Cookie-Value',  /* required property */
        'domain'   : 'localhost',
        'path'     : '/foo',                /* required property */
        'httponly' : true,
        'secure'   : false,
        'expires'  : (new Date()).getTime() + (1000 * 60 * 60)   /* <-- expires in 1 hour */
    },
    // more cookies here...
]
// ...
```

See the [tests](https://github.com/crawlkit/crawlkit/blob/master/test/index.js#L892) for an example.

**Comment by bazjapan** [comment]
thanks for your help.
