### ISSUE TITLE
Limit to crawler depth

### ISSUE THREAD

**Issue by chadbean** [crawlkit/crawlkit#74]
Would you be open to passing in an option to the crawler so that it only crawls _N_ levels deep? For instance, I would like to run the crawler against my web page, and have it only crawl the homepage and all pages linked to on the homepage and nothing further. In this case, I would assume this would be "1 level" deep.

I'd like to help contribute but my JS is a bit weak. If you are open to the idea and have any suggestions on how I can help, feel free to point me in the direction on how you might recommend implementing this. Thanks!

**Comment by joscha** [comment]
@chadbean You should be able to simply adapt the [Finder](http://crawlkit.github.io/crawlkit/docs/Finder.html) - it can have state and also has full access to all URLs being crawled. For an example, see here: https://github.com/crawlkit/crawlkit/blob/master/examples/advanced.js#L8. Please let me know if that works for you.

**Comment by chadbean** [comment]
Thanks, @joscha. I'll take a look!

**Comment by joscha** [comment]
@chadbean did that work for you?

**Comment by chadbean** [comment]
@joscha unfortunately I didn't get too far with it an implementation. Let me know if you have any other advice or feedback.
