### ISSUE TITLE
Error with 2.0.1 release postinstall

### ISSUE THREAD

**Issue by chadbean** [crawlkit/crawlkit#81]
When trying to upgrade via npm from 2.0.0 to 2.0.1, I am receiving this error:

`sh: validate-commit-msg: command not found`

I see the package.json has a postinstall to run the script "validate-commit-msg", but I don't se this file in the repo.

**Comment by joscha** [comment]
ah, it is from dev dependency...

**Comment by joscha** [comment]
fixed via da48d45 and in `2.0.2`. Sorry about that.
